packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@base-ui/react": "1.0.0"

onlyBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver

minimumReleaseAge: false

allowBuilds:
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
