import '@/assets/global.css'
import '@/assets/the-new-css-reset.css'
import { Analytics } from '@vercel/analytics/react'
import { type Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { PropsWithChildren } from 'react'
import { ToastProvider } from '@/components/elements/Toast'
import { SessionProvider } from '@/functions/libs/next-auth/SessionProvider'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SessionProvider>
          <ToastProvider>{children}</ToastProvider>
        </SessionProvider>
        <Analytics />
      </body>
    </html>
  )
}
