export type Theme = 'primary' | 'danger' | (string & {})
export type Variant = 'contained' | 'outlined' | 'ghost' | (string & {})
export type Size = 'small' | 'medium' | 'large' | (string & {})
export type Shape = 'rounded' | 'circle' | (string & {})
export type Align = 'left' | 'center' | 'right' | (string & {})
